### ISSUE TITLE
Build UI from scratch

### ISSUE THREAD

**Issue by Ruchikamodgil** [Ruchikamodgil/AI-Counsellor-WWPHacks#8]
This is the current version of counsello website: https://ai-counselor.web.app/
Targeted UI is given in readme , other changes are also welcomed.

**Comment by ubaida985** [comment]
Are we suppose to change the HTML to make it look like the gif, example the header in the gif has Home, about us, take test and contact. Also, are we allowed to change the structure of the HTML/CSS files?

**Comment by Ruchikamodgil** [comment]
You can develop the UI from scratch as shown in the gif given in readme.

**Comment by Ruchikamodgil** [comment]
@ubaida985 New UI is looking good.
You can also go for issue number #11 if you are interested.

**Comment by ubaida985** [comment]
Okay
